### ISSUE TITLE
Deploying to vercel is throwing an error

### ISSUE THREAD

**Issue by krishnerkar** [gilbarbara/react-spotify-web-playback#124]
**Describe the bug**
I'm using this library, it works fine on localhost, even tho the error in the ss below pops up on localhost time to time it goes away automatically, but now when i deploy it to vercel this happens

**To Reproduce**
Use this library on the latest version of react and nextjs (not beta app dir)

**Expected behavior**
Deploy to vercel without any issues

**Screenshots**
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/49949733/212753430-99f17c7c-7556-4566-92e2-df96ae240cc2.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser : Arc (chrome)

**Comment by gilbarbara** [comment]
Hey @krishnerkar 
Which version are you using?

**Comment by krishnerkar** [comment]
> Hey @krishnerkar Which version are you using?

latest version : `0.11.0`

**Comment by krishnerkar** [comment]
@gilbarbara proposed a fix, please take a look:)

**Comment by krishnerkar** [comment]
suggested a change @gilbarbara please take a look : 

https://github.com/gilbarbara/react-spotify-web-playback/pull/126

**Comment by gilbarbara** [comment]
Can you try with the 0.10.1 version?

**Comment by krishnerkar** [comment]
> Can you try with the 0.10.1 version?

yep works with that thanks:)

**Comment by gilbarbara** [comment]
It should be fixed in 0.11.1

**Comment by krishnerkar** [comment]
> It should be fixed in 0.11.1

sweet, can you ping me here when thats released?

**Comment by gilbarbara** [comment]
It's released...

**Comment by krishnerkar** [comment]
> It's released...

in that case its still not working

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/49949733/213356300-db4745a6-4402-47a7-ad67-671cc67ca513.png">
<img width="379" alt="image" src="https://user-images.githubusercontent.com/49949733/213356308-6db92bb0-3511-4f0c-b864-96a954f53c05.png">

**Comment by gilbarbara** [comment]
Hey @krishnerkar 
You'll need to use a [dynamic import](https://nextjs.org/docs/advanced-features/dynamic-import) for the Player since it doesn't work with SSR.
